# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f55328a1ec5f449e6dbdfbd96b215ed9610ec1d71c40b04f890d2f984402c0c0c1e7823693c4a541c76139eb3850e78d49ceba030fc20082b42e7cdceace84

test:
  secret_key_base: c6e03a9483c5fefa2a7fb7a170bd4f10e049fb2203db30cc781a6c42bcb01ba6416c742fdc4e838b383a26229a93d2df88d0b76dc060a915ee4aaaa689df31b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
